// Biblioteca base de ejercicios. [nombre, grupo, músculo principal, secundarios, equipamiento, instrucciones, errores comunes]
type Row = [string, string, string, string, string, string, string]

const ROWS: Row[] = [
  // PECHO
  ["Press banca", "PECHO", "Pectoral mayor", "Tríceps, deltoides anterior", "Barra y banco", "Escápulas retraídas y pies firmes. Baja la barra controlada hasta la parte baja del pecho y empuja en línea recta hacia arriba.", "Rebotar la barra en el pecho; despegar glúteos del banco; codos totalmente abiertos a 90°."],
  ["Press inclinado con barra", "PECHO", "Pectoral superior", "Deltoides anterior, tríceps", "Barra y banco inclinado", "Banco a 30-45°. Baja la barra a la parte alta del pecho manteniendo escápulas juntas y empuja sin bloquear agresivamente.", "Inclinación excesiva (se vuelve press de hombro); arquear en exceso la zona lumbar."],
  ["Press inclinado con mancuernas", "PECHO", "Pectoral superior", "Deltoides anterior, tríceps", "Mancuernas y banco inclinado", "Banco a 30°. Baja las mancuernas con codos a ~45° del torso hasta sentir estiramiento y empuja juntándolas arriba.", "Chocar las mancuernas; bajar poco el rango; perder la retracción escapular."],
  ["Press plano con mancuernas", "PECHO", "Pectoral mayor", "Tríceps, deltoides anterior", "Mancuernas y banco", "Mancuernas a la altura del pecho, baja controlado con codos a 45° y empuja arriba en arco suave.", "Bajar sin control; codos demasiado abiertos."],
  ["Press en máquina", "PECHO", "Pectoral mayor", "Tríceps", "Máquina", "Ajusta el asiento para que las manijas queden a la altura del pecho. Empuja sin bloquear codos y regresa lento.", "Asiento mal ajustado; despegar la espalda del respaldo."],
  ["Aperturas con mancuernas", "PECHO", "Pectoral mayor", "Deltoides anterior", "Mancuernas y banco", "Codos ligeramente flexionados y fijos. Abre en arco hasta sentir estiramiento y cierra apretando el pecho.", "Flexionar y extender codos (convertirlo en press); bajar demasiado con mucho peso."],
  ["Aperturas en polea (cruce)", "PECHO", "Pectoral mayor", "Deltoides anterior", "Poleas", "Paso adelante, torso levemente inclinado. Lleva las manos al frente en arco y aprieta al centro.", "Usar impulso del cuerpo; encoger hombros."],
  ["Pec deck", "PECHO", "Pectoral mayor", "Deltoides anterior", "Máquina", "Espalda pegada al respaldo, cierra los brazos al frente con control y vuelve lento.", "Rango corto; hombros adelantados."],
  ["Fondos en paralelas", "PECHO", "Pectoral inferior", "Tríceps, deltoides anterior", "Paralelas", "Torso ligeramente inclinado hacia delante. Baja hasta que los hombros queden a la altura de los codos y empuja.", "Bajar demasiado con dolor de hombro; balancear las piernas."],
  ["Flexiones de brazos", "PECHO", "Pectoral mayor", "Tríceps, core", "Peso corporal", "Cuerpo en línea recta, manos algo más anchas que los hombros. Baja el pecho casi al suelo y empuja.", "Cadera caída; codos a 90° del torso; rango incompleto."],
  // ESPALDA
  ["Dominadas", "ESPALDA", "Dorsal ancho", "Bíceps, romboides", "Barra fija", "Agarre prono algo más ancho que hombros. Tira llevando el pecho a la barra y baja completamente.", "Balanceo; no extender los brazos abajo; tirar solo con brazos."],
  ["Dominadas asistidas", "ESPALDA", "Dorsal ancho", "Bíceps", "Máquina / banda", "Igual que la dominada, con asistencia. Controla la bajada.", "Usar demasiada asistencia; rango corto."],
  ["Jalón al pecho", "ESPALDA", "Dorsal ancho", "Bíceps, redondo mayor", "Polea alta", "Pecho arriba, lleva la barra a la parte alta del pecho bajando los codos. Sube controlado.", "Llevar la barra detrás de la nuca; balancearse hacia atrás."],
  ["Jalón agarre cerrado", "ESPALDA", "Dorsal ancho", "Bíceps", "Polea alta", "Con triángulo, tira hacia el esternón manteniendo el torso estable.", "Usar el impulso del torso."],
  ["Remo con barra", "ESPALDA", "Dorsal ancho", "Romboides, trapecio, bíceps", "Barra", "Bisagra de cadera a ~45°, espalda neutra. Tira la barra al ombligo y baja controlado.", "Redondear la espalda; levantar el torso en cada repetición."],
  ["Remo con mancuerna", "ESPALDA", "Dorsal ancho", "Romboides, bíceps", "Mancuerna y banco", "Una mano y rodilla apoyadas. Tira la mancuerna hacia la cadera con el codo pegado.", "Rotar el torso; tirar hacia el hombro."],
  ["Remo en polea baja", "ESPALDA", "Dorsal ancho", "Romboides, bíceps", "Polea baja", "Torso erguido, tira el agarre hacia el abdomen juntando escápulas.", "Balancear el torso adelante y atrás."],
  ["Remo en máquina", "ESPALDA", "Dorsal ancho", "Romboides", "Máquina", "Pecho apoyado, tira con los codos hacia atrás y aprieta las escápulas.", "Encoger hombros; rango corto."],
  ["Pullover en polea", "ESPALDA", "Dorsal ancho", "Redondo mayor", "Polea alta", "Brazos casi extendidos, lleva la barra en arco hasta los muslos sintiendo el dorsal.", "Flexionar codos; mover la cadera."],
  ["Peso muerto", "ESPALDA", "Erectores espinales", "Glúteos, isquiotibiales, trapecio", "Barra", "Barra sobre el medio del pie, espalda neutra. Empuja el suelo y extiende cadera y rodillas a la vez.", "Redondear la espalda; alejar la barra del cuerpo; hiperextender arriba."],
  ["Hiperextensiones", "ESPALDA", "Erectores espinales", "Glúteos", "Banco romano", "Cadera en el borde del banco. Baja con espalda neutra y sube hasta alinear el cuerpo.", "Hiperextender la zona lumbar arriba."],
  ["Face pull", "HOMBROS", "Deltoides posterior", "Manguito rotador, trapecio medio", "Polea con cuerda", "Polea a la altura de la cara. Tira hacia la frente separando las manos y rotando externamente.", "Usar demasiado peso; tirar hacia el pecho."],
  // HOMBROS
  ["Press militar", "HOMBROS", "Deltoides anterior", "Tríceps, deltoides lateral", "Barra", "De pie, glúteos y abdomen firmes. Empuja la barra por encima de la cabeza pasando cerca de la cara.", "Arquear la zona lumbar; empujar la barra hacia adelante."],
  ["Press de hombros con mancuernas", "HOMBROS", "Deltoides anterior", "Tríceps, deltoides lateral", "Mancuernas y banco", "Sentado con respaldo, empuja las mancuernas desde la altura de las orejas hasta arriba.", "Bajar poco; perder la posición de la espalda."],
  ["Press Arnold", "HOMBROS", "Deltoides", "Tríceps", "Mancuernas", "Inicia con palmas hacia ti, rota mientras empujas hasta terminar con palmas al frente.", "Hacerlo rápido sin control."],
  ["Elevaciones laterales", "HOMBROS", "Deltoides lateral", "Trapecio superior", "Mancuernas", "Codos levemente flexionados. Eleva los brazos hacia los lados hasta la altura de los hombros.", "Balancear el cuerpo; subir por encima del hombro encogiendo el trapecio."],
  ["Elevaciones laterales en polea", "HOMBROS", "Deltoides lateral", "", "Polea baja", "De lado a la polea, eleva el brazo hasta la altura del hombro con tensión constante.", "Girar el torso."],
  ["Elevaciones frontales", "HOMBROS", "Deltoides anterior", "", "Mancuernas / disco", "Eleva al frente hasta la altura de los ojos, baja lento.", "Balanceo con la espalda."],
  ["Pájaros (deltoides posterior)", "HOMBROS", "Deltoides posterior", "Romboides", "Mancuernas", "Torso inclinado, abre los brazos hacia los lados con codos semiflexionados.", "Tirar con la espalda; usar mucho peso."],
  ["Encogimientos de hombros", "HOMBROS", "Trapecio superior", "", "Mancuernas / barra", "Sube los hombros hacia las orejas, pausa y baja lento.", "Rotar los hombros; rango corto."],
  // BRAZOS
  ["Curl con barra", "BRAZOS", "Bíceps", "Braquial", "Barra", "Codos pegados al torso, flexiona hasta arriba sin mover los hombros y baja controlado.", "Balancear el torso; adelantar los codos."],
  ["Curl con mancuernas", "BRAZOS", "Bíceps", "Braquial", "Mancuernas", "Supina la muñeca mientras subes. Alterna o simultáneo.", "Impulso con la cadera."],
  ["Curl martillo", "BRAZOS", "Braquial", "Braquiorradial, bíceps", "Mancuernas", "Agarre neutro, flexiona manteniendo codos fijos.", "Mover los codos hacia adelante."],
  ["Curl predicador", "BRAZOS", "Bíceps", "Braquial", "Banco Scott", "Brazos apoyados, baja hasta casi extender y sube apretando.", "Rebotar abajo; levantar los codos del pad."],
  ["Curl en polea", "BRAZOS", "Bíceps", "", "Polea baja", "Tensión constante, codos fijos a los lados.", "Inclinarse hacia atrás."],
  ["Extensión de tríceps en polea", "BRAZOS", "Tríceps", "", "Polea alta", "Codos pegados al cuerpo, extiende completamente y vuelve controlado.", "Separar los codos; inclinar demasiado el torso."],
  ["Press francés", "BRAZOS", "Tríceps", "", "Barra Z y banco", "Acostado, baja la barra hacia la frente flexionando solo los codos y extiende.", "Abrir los codos; mover los hombros."],
  ["Extensión de tríceps sobre la cabeza", "BRAZOS", "Tríceps (porción larga)", "", "Mancuerna / polea", "Brazos arriba, baja detrás de la cabeza y extiende.", "Arquear la espalda baja."],
  ["Fondos en banco", "BRAZOS", "Tríceps", "Pectoral, deltoides anterior", "Banco", "Manos en el banco, baja flexionando codos hasta 90° y empuja.", "Bajar demasiado forzando el hombro."],
  ["Press banca agarre cerrado", "BRAZOS", "Tríceps", "Pectoral", "Barra y banco", "Manos al ancho de hombros, codos cerca del cuerpo.", "Agarre demasiado estrecho que carga las muñecas."],
  // PIERNAS
  ["Sentadilla con barra", "PIERNAS", "Cuádriceps", "Glúteos, aductores, core", "Barra y rack", "Pies al ancho de hombros, pecho arriba. Baja con control hasta al menos paralelo y sube empujando el suelo.", "Rodillas hacia adentro; talones levantados; redondear la espalda abajo."],
  ["Sentadilla frontal", "PIERNAS", "Cuádriceps", "Glúteos, core", "Barra y rack", "Barra sobre deltoides anteriores, codos altos, torso vertical.", "Codos caídos; perder la verticalidad."],
  ["Sentadilla goblet", "PIERNAS", "Cuádriceps", "Glúteos, core", "Mancuerna / kettlebell", "Sostén el peso frente al pecho y baja entre las piernas con el torso erguido.", "Talones arriba; rodillas colapsando."],
  ["Prensa de piernas", "PIERNAS", "Cuádriceps", "Glúteos", "Máquina", "Pies al ancho de caderas. Baja hasta 90° sin despegar la zona lumbar y empuja.", "Bloquear las rodillas arriba; despegar la cadera del asiento."],
  ["Hack squat", "PIERNAS", "Cuádriceps", "Glúteos", "Máquina", "Espalda apoyada, baja profundo controlando y sube.", "Rango corto; rodillas hacia adentro."],
  ["Extensión de cuádriceps", "PIERNAS", "Cuádriceps", "", "Máquina", "Extiende las rodillas hasta arriba, pausa y baja lento.", "Usar impulso; rango incompleto."],
  ["Zancadas", "PIERNAS", "Cuádriceps", "Glúteos", "Mancuernas", "Paso largo, baja la rodilla trasera casi al suelo y empuja con la pierna delantera.", "Rodilla delantera hacia adentro; paso muy corto."],
  ["Sentadilla búlgara", "PIERNAS", "Cuádriceps", "Glúteos", "Mancuernas y banco", "Pie trasero en el banco, baja vertical controlando.", "Pie delantero muy cerca del banco; perder equilibrio por prisa."],
  ["Peso muerto rumano", "PIERNAS", "Isquiotibiales", "Glúteos, erectores", "Barra / mancuernas", "Rodillas semiflexionadas, lleva la cadera atrás deslizando la barra por los muslos hasta sentir estiramiento.", "Redondear la espalda; flexionar demasiado las rodillas."],
  ["Curl femoral acostado", "PIERNAS", "Isquiotibiales", "Gemelos", "Máquina", "Cadera pegada al banco, flexiona las rodillas y baja lento.", "Levantar la cadera."],
  ["Curl femoral sentado", "PIERNAS", "Isquiotibiales", "", "Máquina", "Ajusta el rodillo sobre los tobillos y flexiona con control.", "Rango corto."],
  ["Elevación de talones de pie", "PIERNAS", "Gemelos", "Sóleo", "Máquina / escalón", "Sube a puntas lo más alto posible, pausa y baja estirando.", "Rebotar; rango corto."],
  ["Elevación de talones sentado", "PIERNAS", "Sóleo", "Gemelos", "Máquina", "Rodillas a 90°, sube y baja completo con pausa.", "Rebotar abajo."],
  ["Step up", "PIERNAS", "Cuádriceps", "Glúteos", "Cajón y mancuernas", "Sube al cajón empujando con la pierna de arriba sin impulsarte con la de abajo.", "Impulsarse con la pierna trasera."],
  // GLÚTEOS
  ["Hip thrust", "GLUTEOS", "Glúteo mayor", "Isquiotibiales", "Barra y banco", "Escápulas en el banco, barra sobre la cadera. Extiende la cadera hasta alinear torso y muslos, aprieta arriba.", "Hiperextender la lumbar; empujar con las puntas."],
  ["Puente de glúteos", "GLUTEOS", "Glúteo mayor", "Isquiotibiales", "Peso corporal / barra", "Acostado, eleva la cadera apretando glúteos y baja controlado.", "Arquear la espalda."],
  ["Patada de glúteo en polea", "GLUTEOS", "Glúteo mayor", "", "Polea baja", "Extiende la cadera hacia atrás sin arquear la espalda.", "Rotar la cadera."],
  ["Abducción de cadera en máquina", "GLUTEOS", "Glúteo medio", "", "Máquina", "Abre las piernas con control y vuelve lento.", "Usar impulso."],
  ["Peso muerto sumo", "GLUTEOS", "Glúteos", "Aductores, cuádriceps", "Barra", "Postura amplia, agarre dentro de las piernas, pecho arriba y extiende cadera.", "Rodillas hacia adentro."],
  // CORE
  ["Plancha", "CORE", "Transverso abdominal", "Recto abdominal, oblicuos", "Peso corporal", "Antebrazos bajo los hombros, cuerpo en línea, aprieta glúteos y abdomen.", "Cadera caída o muy alta."],
  ["Plancha lateral", "CORE", "Oblicuos", "Glúteo medio", "Peso corporal", "Apoyado en un antebrazo, cadera arriba en línea recta.", "Dejar caer la cadera."],
  ["Crunch abdominal", "CORE", "Recto abdominal", "", "Peso corporal", "Flexiona el tronco despegando escápulas, exhala arriba.", "Tirar del cuello con las manos."],
  ["Crunch en polea", "CORE", "Recto abdominal", "", "Polea alta", "De rodillas, flexiona el tronco llevando los codos a los muslos.", "Mover la cadera en vez del tronco."],
  ["Elevación de piernas colgado", "CORE", "Recto abdominal inferior", "Flexores de cadera", "Barra fija", "Colgado, eleva las piernas controlando sin balanceo.", "Balancearse."],
  ["Rueda abdominal", "CORE", "Recto abdominal", "Dorsal, core", "Rueda", "De rodillas, rueda hacia adelante manteniendo la espalda neutra y vuelve.", "Arquear la lumbar."],
  ["Pallof press", "CORE", "Oblicuos", "Transverso", "Polea / banda", "De lado a la polea, empuja al frente resistiendo la rotación.", "Girar el torso."],
  ["Dead bug", "CORE", "Transverso abdominal", "", "Peso corporal", "Boca arriba, extiende brazo y pierna contrarios manteniendo la lumbar pegada al suelo.", "Despegar la zona lumbar."],
  ["Russian twist", "CORE", "Oblicuos", "", "Disco / balón", "Sentado con torso inclinado, rota de lado a lado.", "Mover solo los brazos."],
  // CARDIO / FULLBODY
  ["Caminadora inclinada", "CARDIO", "Cardiovascular", "Glúteos, gemelos", "Caminadora", "Camina a ritmo sostenido con inclinación 8-12%, sin apoyarte en las barras.", "Sujetarse de las barras."],
  ["Bicicleta estática", "CARDIO", "Cardiovascular", "Cuádriceps", "Bicicleta", "Mantén cadencia constante; ajusta el asiento a la altura de la cadera.", "Asiento muy bajo."],
  ["Elíptica", "CARDIO", "Cardiovascular", "", "Elíptica", "Ritmo constante, postura erguida.", "Encorvarse."],
  ["Remo ergómetro", "CARDIO", "Cardiovascular", "Espalda, piernas", "Remo", "Piernas – cadera – brazos al tirar; brazos – cadera – piernas al volver.", "Tirar solo con brazos."],
  ["Saltar la cuerda", "CARDIO", "Cardiovascular", "Gemelos", "Cuerda", "Saltos pequeños sobre puntas, muñecas giran la cuerda.", "Saltos muy altos."],
  ["Burpees", "FULLBODY", "Cuerpo completo", "", "Peso corporal", "Sentadilla, plancha, flexión, salto. Ritmo constante.", "Cadera caída en la plancha."],
  ["Kettlebell swing", "FULLBODY", "Glúteos", "Isquiotibiales, core, hombros", "Kettlebell", "Bisagra de cadera explosiva; los brazos solo guían la pesa.", "Hacer sentadilla en vez de bisagra; levantar con los brazos."],
  ["Thruster", "FULLBODY", "Cuádriceps", "Hombros, glúteos", "Barra / mancuernas", "Sentadilla frontal y al subir empuja la carga sobre la cabeza en un solo movimiento.", "Separar el movimiento en dos."],
  ["Farmer walk", "FULLBODY", "Agarre", "Trapecio, core", "Mancuernas", "Camina erguido con peso pesado a cada lado.", "Inclinarse hacia un lado."],
]

export const DEFAULT_EXERCISES = ROWS.map(([name, muscleGroup, primaryMuscle, secondaryMuscles, equipment, instructions, commonMistakes]) => ({
  name, muscleGroup, primaryMuscle, secondaryMuscles: secondaryMuscles || null, equipment, instructions, commonMistakes,
}))
