-- Add channel to CoachMessage (COACHING | NUTRITION)
ALTER TABLE "CoachMessage" ADD COLUMN IF NOT EXISTS "channel" TEXT NOT NULL DEFAULT 'COACHING';

-- Add type to CoachingSlot (COACHING | NUTRITION)
ALTER TABLE "CoachingSlot" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'COACHING';
